name: Test Python Bot

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov  # Only need to add this as others are in requirements.txt

      - name: Run all tests with coverage
        run: |
          PYTHONPATH=. pytest tests --cov=bot --cov-report=xml

      - name: Run specific test file (if needed)
        run: |
          PYTHONPATH=. pytest tests/test1.py

      - name: Generate complexity reports
        run: |
          radon cc bot -a -nc > radon_report.txt
          xenon bot --max-absolute C --max-modules B --max-average A > xenon_report.txt
          
      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-reports
          path: |
            radon_report.txt
            xenon_report.txt
            coverage.xml
