name: Test Python Bot

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest radon xenon

      - name: Run specific test file
        run: |
          PYTHONPATH=. pytest tests/test1.py

      - name: Analyze cyclomatic complexity with radon
        run: |
          radon cc bot -a

      - name: Highlight complexity issues with xenon
        run: |
          xenon bot --max-absolute C --max-modules B --max-average A
